### ISSUE TITLE
При открытии файла формы "Текст" восстанавливается без пробелов

### ISSUE THREAD

**Issue by ConSmit** [ahyahy/OneScriptFormsDesigner#3]
При открытии сохраненной ранее формы реквизит Текст во всех элементах теряет пробелы.  (в файле "Комментарий к подключению", восстановилось "Комментарийкподключению")

**Comment by ahyahy** [comment]
Постараюсь завтра, то есть сегодня уже исправить, у нас 0 часов26 минут. За найденную ошибку спасибо. Проблема знакомая, видимо пропустил при тестировании.

**Comment by ahyahy** [comment]
Выпустил новый релиз 1.0.1.0. В нём ошибка исправлена, проверьте пожалуйста.

**Comment by ConSmit** [comment]
Все работает! Спасибо!
